FROM python:3.10-alpine

RUN pip install kubernetes
RUN pip install datetime
RUN pip install pytz

# Los directorios estan situados de acuerdo a la maquina virtual, que es donde se ha creado la imagen
COPY CRD/microservice_definition.yaml /CRD/
COPY mikrozerbitzu_kontroladorea.py /
COPY utils.py /

WORKDIR /

CMD ["python3", "mikrozerbitzu_kontroladorea.py"]
