apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aplikazio-kontroladore-baimen-esleipena
subjects:
- kind: User
  name: system:serviceaccount:default:default
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: aplikazio-kontroladore-baimenak
  apiGroup: rbac.authorization.k8s.io