apiVersion: ehu.gcis.org/v1alpha1
kind: Application
metadata:
  name: nire-fog-aplikazioa
spec:
  microservices: 
    - name: zenbakiensorkuntza
      service: BalioNaturalak
      image: ekhurtado/gcis:zenbakien-sorkuntza
      customization: '{"custom_mota": "ausazkoa", "custom_hasierakobalioa": 5}'
      outPort:
        name: zenbakiensorkuntza-oport
        dataType: TZenbaki
        protocol: HTTP
    - name: zenbakienprozesamendua
      service: BalioaHanditu
      image: ekhurtado/gcis:zenbakien-prozesamendua
      customization: '{"custom_urratsa": 2}'
      inPort:
        name: zenbakienprozesamendua-iport
        dataType: TZenbaki
        protocol: HTTP
        number: '6000'
      outPort:
        name: zenbakienprozesamendua-oport
        dataType: TZenbaki
        protocol: HTTP
    - name: zenbakienaurkezpena
      service: PantailaAurkezpen
      image: ekhurtado/gcis:zenbakien-aurkezpena
      inPort:
        name: zenbakienaurkezpena-iport
        dataType: TZenbaki
        protocol: HTTP
        number: '7000'
  channels: 
    - from: zenbakiensorkuntza-oport
      to: zenbakienprozesamendua-iport
    - from: zenbakienprozesamendua-oport
      to: zenbakienaurkezpena-iport