apiVersion: ehu.gcis.org/v1alpha1
kind: Application
metadata:
  name: dataprocessing
spec:
  microservices: 
    - name: exist
      service: GetAssemblyStationData
      image: ekhurtado/gcis:exist
      customization: '{"custom_stationID": "AS1"}'
      outPort:
        name: exist-oport
        dataType: TDBStation
        protocol: HTTP
    - name: assemblystation
      service: ProcessingOEE
      image: ekhurtado/gcis:assembly_station
      inPort:
        name: assemblystation-iport
        dataType: TDBStation
        protocol: HTTP
        number: '6000'
      outPort:
        name: assemblystation-oport
        dataType: TStationOEE
        protocol: HTTP
    - name: oeeevents
      service: NotifyOperator
      image: ekhurtado/gcis:oee_events
      customization: '{"custom_threshold": 70}'
      inPort:
        name: oeeevents-iport
        dataType: TStationOEE
        protocol: HTTP
        number: '7000'
      outPort:
        name: oeeevents-oport
        dataType: TDBOEE
        protocol: HTTP
    - name: influx
      service: StoreOEEData
      image: ekhurtado/gcis:influx
      inPort:
        name: influx-iport
        dataType: TDBOEE
        protocol: HTTP
        number: '8000'
  channels: 
    - from: exist-oport
      to: assemblystation-iport
    - from: assemblystation-oport
      to: oeeevents-iport
    - from: oeeevents-oport
      to: influx-iport