apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applications.ehu.gcis.org
spec:
  group: ehu.gcis.org
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [ microservices, channels ]
              properties:
                name:
                  type: string
                microservices:
                  type: array
                  items:
                    type: object
                    required: [ name, image, service ]
                    properties:
                      name:
                        type: string
                      image:
                        type: string
                      service:
                        type: string
                      customization:
                        type: string
                      inPort:
                        type: object
                        required: [ name, protocol, dataType, number ]
                        properties:
                          name:
                            type: string
                          protocol:
                            type: string
                          dataType:
                            type: string
                          number:
                            type: string
                      outPort:
                        type: object
                        required: [ name, protocol, dataType ]
                        properties:
                          name:
                            type: string
                          protocol:
                            type: string
                          dataType:
                            type: string
                channels:
                  type: array
                  items:
                    type: object
                    required: [ from, to ]
                    properties:
                      from:
                        type: string
                      to:
                        type: string
            status:
              type: object
              properties:
                microservices:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      status:
                        type: string
                ready:
                  type: string
      additionalPrinterColumns:
        - jsonPath: .status.ready
          name: Ready
          type: string
          description: Readiness of the created resource
          priority: 0
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
          priority: 0
      subresources:
        status: {}

  scope: Namespaced
  names:
    plural: applications
    singular: application
    kind: Application
    shortNames:
      - app