apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: microservices.ehu.gcis.org
spec:
  group: ehu.gcis.org
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [name, image, service]
              properties:
                name:
                  type: string
                image:
                  type: string
                service:
                  type: string
                customization:
                  type: string
                inPort:
                  type: object
                  required: [name, protocol, dataType, number]
                  properties:
                    name:
                      type: string
                    protocol:
                      type: string
                    dataType:
                      type: string
                    number:
                      type: string
                outPort:
                  type: object
                  required: [ name, protocol, dataType ]
                  properties:
                    name:
                      type: string
                    protocol:
                      type: string
                    dataType:
                      type: string
            status:
              type: object
              properties:
                situation:
                  type: string
      additionalPrinterColumns:
        - jsonPath: .spec.name
          name: MicrosvcName
          description: Name of the microservice
          type: string
          priority: 0
        - jsonPath: .spec.service
          name: Service
          description: Service of the microservice
          type: string
          priority: 0
        - jsonPath: .status.situation
          name: Status
          type: string
          priority: 0
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
          priority: 0
        - jsonPath: .spec.image
          name: Image
          type: string
          priority: 1
      subresources:
        status: {}

  scope: Namespaced
  names:
    plural: microservices
    singular: microservice
    kind: Microservice
    shortNames:
      - microsvc
