FROM openjdk:11-jdk
#FROM adoptopenjdk:11-jre-hotspot

#COPY zenbakienAurkezpena.jar /
COPY zenbakienAurkezpena.java /

RUN javac zenbakienAurkezpena.java

#CMD ["java", "-jar", "zenbakienAurkezpena.jar"]
CMD ["java", "zenbakienAurkezpena"]