#FROM mcr.microsoft.com/dotnet/runtime:5.0-alpine3.13-amd64
#CMD ["dotnet", "out/NetCore.Docker.dll"]
#=======
FROM mcr.microsoft.com/dotnet/aspnet:7.0

COPY ZenbakienSorkuntza /ZenbakienSorkuntza

WORKDIR /ZenbakienSorkuntza

ENV SERVICE=IntegerValue

CMD ["dotnet", "out/DotNet.Docker.dll"]
